#!/bin/sh

xrandr --output DP-1 --auto --gamma 0.87 --scale 1.0x1.0 --output eDP-1 --right-of DP-1 --auto --scale 1.0x1.0
#xrandr --output HDMI-1 --auto --gamma 0.87 --scale 1.0x1.0 --output eDP-1 --right-of HDMI-1 --auto --scale 1.0x1.0
#picom -CG --backend="glx" --no-use-damage --vsync --no-fading-openclose &
picom &
